title: EL's Shelf (dev)
description: >- 
  Eryn's reading journal (dev)
baseurl: / 
url: "https://ayeryn.github.io" 
# theme: minima
remote_theme: "jeffreytse/jekyll-theme-yat"

plugins:
  - jekyll-feed
  - jekyll-remote-theme




















