# Site 
title: EL's Shelf (dev)
description: >- 
  Eryn's reading journal (dev)
baseurl: / 
url: "https://ayeryn.github.io" 

# Author
author:
  name: EL
  email: test@test.com

# Build
# theme: jekyll-theme-yat
remote_theme: broccolini/swiss
theme_color: yellow
plugins:
  - jekyll-feed
  - jekyll-github-metadata
github:
  repository: ayeryn/els-shelf-dev




















