name: Deploy to els-shelf (live)

on:
  push:
    branches:
      - main # Trigger on push to the 'main' branch
    paths-ignore:
      - "README.md"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout els-shelf-dev repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add els-shelf-live remote
        run: |
          git remote add els-shelf-live https://github.com/ayeryn/els-shelf-live.git
          git fetch els-shelf-live

      - name: Checkout deploy branch of els-shelf-live
        run: |
          git checkout -b deploy els-shelf-live/deploy

      - name: Merge main into deploy
        run: |
          git merge main --no-edit

      - name: Push changes to els-shelf-live
        run: |
          git push proj_live deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
